### ISSUE TITLE
Upgrade analyzer dependency to 6.4.0 to support Dart >3.2.0

### ISSUE THREAD

**Issue by point-source** [helightdev/dogs#3]
**Affected packages**
- dogs_generator

**Describe the bug**
When I run the generator, I get this warning:
```
Your current `analyzer` version may not fully support your current SDK version.

Analyzer language version: 3.1.0
SDK language version: 3.2.0

Please update to the latest `analyzer` version (6.4.0) by running
`flutter packages upgrade`.

If you are not getting the latest version by running the above command, you
can try adding a constraint like the following to your pubspec to start
diagnosing why you can't get the latest version:

dev_dependencies:
  analyzer: ^6.4.0
```

**To Reproduce**
1. Use the dart 3.2.0 sdk or higher to create a project
2. Add dogs_core and dogs_generator
3. Create a serializable class
4. Run the build runner

**Expected behavior**
dogs should support the latest sdk

**Additional context**
Dart SDK version: 3.2.5 (stable) (Tue Jan 16 15:02:13 2024 +0000) on "macos_arm64"

**Comment by helightdev** [comment]
Updated with dogs_generator: ^5.1.2
